import {defineField, defineType} from 'sanity'

export const siteSettingsType = defineType({
  name: 'siteSettings',
  title: 'Ustawienia Strony (Site Settings)',
  type: 'document',
  groups: [
    { name: 'basic', title: 'Podstawowe', default: true },
    { name: 'colors', title: 'Kolory & Motyw' },
    { name: 'hero', title: 'Sekcja Główna (Hero)' },
    { name: 'buttons', title: 'Przyciski' },
    { name: 'sections', title: 'Tytuły Sekcji' },
    { name: 'footer', title: 'Stopka' },
    { name: 'seo', title: 'SEO & Metadane' },
  ],
  fields: [
    // --- PODSTAWOWE ---
    defineField({
      name: 'title',
      title: 'Nazwa Klubu',
      type: 'string',
      description: 'Główna nazwa klubu wyświetlana na stronie (np. Nova City FC)',
      validation: (Rule) => Rule.required(),
      group: 'basic',
    }),
    defineField({
      name: 'logo',
      title: 'Logo Klubu',
      type: 'image',
      description: 'Główne logo klubu w formacie PNG lub SVG',
      options: { hotspot: true },
      group: 'basic',
    }),
    defineField({
      name: 'logoSize',
      title: 'Wysokość Logo (w pikselach)',
      type: 'number',
      description: 'Zalecana wartość to między 40 a 120. Domyślnie 48.',
      initialValue: 48,
      validation: (Rule) => Rule.min(20).max(200),
      group: 'basic',
    }),
    defineField({
      name: 'favicon',
      title: 'Favicon',
      type: 'image',
      description: 'Ikonka w zakładce przeglądarki (powinna być kwadratowa).',
      group: 'basic',
    }),
    defineField({
      name: 'mainMenu',
      title: 'Główne Menu (Nawigacja)',
      type: 'array',
      description: 'Zbuduj pasek nawigacyjny. Możesz dodawać pojedyncze linki lub rozwijane listy.',
      of: [{type: 'menuItem'}, {type: 'menuDropdown'}],
      group: 'basic',
    }),

    // --- KOLORY ---
    defineField({
      name: 'primaryColor',
      title: 'Główny Kolor Akcentu (Primary)',
      type: 'string',
      description: 'Główny kolor używany dla nazwy klubu, obramowań, przycisków i ikon. Format HEX (np. #d4af37)',
      initialValue: '#d4af37',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'accentTextColor',
      title: 'Drugi Kolor Tekstu (Akcent)',
      type: 'string',
      description: 'Kolor wyróżnionego tekstu (np. drugiego słowa w nazwie klubu w nagłówkach). Format HEX.',
      initialValue: '#d4af37',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'backgroundColor',
      title: 'Główny Kolor Tła Strony',
      type: 'string',
      description: 'Główny kolor tła dla całej strony. Format HEX.',
      initialValue: '#0a0a0a',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'headerBackgroundColor',
      title: 'Kolor Tła Nawigacji (Header)',
      type: 'string',
      description: 'Tło górnego paska nawigacyjnego. Format HEX.',
      initialValue: '#050505',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'footerBackgroundColor',
      title: 'Kolor Tła Stopki',
      type: 'string',
      description: 'Tło sekcji ze stopką na samym dole. Format HEX.',
      initialValue: '#000000',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'secondaryColor',
      title: 'Tło Pomocnicze (Secondary)',
      type: 'string',
      description: 'Tło dla kart (np. Aktualności), elementów menu. Format HEX.',
      initialValue: '#121212',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'foregroundColor',
      title: 'Kolor Tekstu (Foreground)',
      type: 'string',
      description: 'Główny kolor napisów na stronie. Format HEX.',
      initialValue: '#f5f5f5',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'decorationsEnabled',
      title: 'Pokaż Motywy Dekoracyjne',
      type: 'boolean',
      description: 'Zaznacz, aby wyświetlać dodatkowe akcenty graficzne (ukośne linie, poświaty).',
      initialValue: true,
      group: 'colors',
    }),
    defineField({
      name: 'decorationsColor',
      title: 'Kolor Motywów Dekoracyjnych',
      type: 'string',
      description: 'Podaj kolor w formacie HEX. Jeśli puste, użyty zostanie domyślny.',
      initialValue: '#FBBF24',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),

    defineField({
      name: 'newsGradientStart',
      title: 'Animacja Aktualności: Kolor 1',
      type: 'string',
      description: 'Format HEX. Zostaw puste, aby użyć jasnego (Foreground).',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'newsGradientMid',
      title: 'Animacja Aktualności: Kolor 2',
      type: 'string',
      description: 'Format HEX. Zostaw puste, aby użyć głównego (Primary).',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),
    defineField({
      name: 'newsGradientEnd',
      title: 'Animacja Aktualności: Kolor 3',
      type: 'string',
      description: 'Format HEX. Zostaw puste, aby użyć tła (Background).',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'colors',
    }),

    // --- HERO ---
    defineField({
      name: 'heroBackground',
      title: 'Tło sekcji głównej (Hero)',
      type: 'image',
      description: 'Główne zdjęcie w tle na samej górze strony.',
      options: { hotspot: true },
      group: 'hero',
    }),
    defineField({
      name: 'heroTitle',
      title: 'Tytuł w sekcji głównej (Hero)',
      type: 'string',
      description: 'Wielki napis na samej górze. Jeśli zostawisz puste, użyta zostanie Nazwa Klubu.',
      group: 'hero',
    }),
    defineField({
      name: 'heroDescription',
      title: 'Opis w sekcji głównej (Hero)',
      type: 'text',
      description: 'Tekst widoczny pod tytułem w sekcji głównej.',
      group: 'hero',
    }),
    defineField({
      name: 'syncHeroWithFooter',
      title: 'Użyj opisu ze stopki w Hero',
      type: 'boolean',
      description: 'Zaznacz, aby tekst Hero pobierał się z pola "Opis w stopce".',
      initialValue: false,
      group: 'hero',
    }),

    // --- BUTTONS ---
    defineField({
      name: 'buttonColorNavbar',
      title: 'Nawigacja: Przycisk "Dołącz do klubu"',
      type: 'string',
      description: 'Format HEX. Zostaw puste, aby użyć koloru dekoracji/głównego.',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'buttons',
    }),
    defineField({
      name: 'buttonColorNews',
      title: 'Aktualności: Przycisk "Czytaj więcej"',
      type: 'string',
      description: 'Format HEX. Zostaw puste, aby użyć koloru głównego.',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'buttons',
    }),
    defineField({
      name: 'buttonColorFooter',
      title: 'Stopka: Przycisk "Newsletter"',
      type: 'string',
      description: 'Format HEX. Zostaw puste, aby użyć koloru głównego.',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'buttons',
    }),

    // --- SECTIONS ---
    defineField({
      name: 'newsSectionTitle',
      title: 'Tytuł: Aktualności',
      type: 'string',
      description: 'Napis nad listą aktualności (np. "Wiadomości").',
      initialValue: 'AKTUALNOŚCI',
      group: 'sections',
    }),
    defineField({
      name: 'newsSectionTitleColor',
      title: 'Kolor Tytułu: Aktualności',
      type: 'string',
      description: 'Format HEX. Zostaw puste by użyć koloru głównego (Primary).',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'sections',
    }),
    defineField({
      name: 'sponsorsSectionTitle',
      title: 'Tytuł: Sponsorzy',
      type: 'string',
      description: 'Napis nad logotypami sponsorów (np. "Nasi Partnerzy").',
      initialValue: 'SPONSORZY',
      group: 'sections',
    }),
    defineField({
      name: 'sponsorsSectionTitleColor',
      title: 'Kolor Tytułu: Sponsorzy',
      type: 'string',
      description: 'Format HEX. Zostaw puste by użyć koloru głównego (Primary).',
      validation: (Rule) => Rule.regex(/^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/, { name: 'hex color', invert: false }),
      group: 'sections',
    }),

    // --- FOOTER ---
    defineField({
      name: 'footerDescription',
      title: 'Opis w stopce',
      type: 'text',
      description: 'Krótki opis klubu widoczny w lewej części stopki.',
      group: 'footer',
    }),
    defineField({
      name: 'footerCopyright',
      title: 'Tekst Praw Autorskich (Copyright)',
      type: 'string',
      description: 'Tekst wyświetlany na samym dole stopki. Zostaw puste, aby użyć domyślnego.',
      group: 'footer',
    }),
    
    // --- SEO & METADATA ---
    defineField({
      name: 'seoTitle',
      title: 'Globalny Tytuł SEO',
      type: 'string',
      description: 'Tytuł strony dla wyszukiwarek (np. "Wicher Gdynia - Oficjalna Strona"). Jeśli puste, użyta zostanie Nazwa Klubu.',
      group: 'seo',
    }),
    defineField({
      name: 'seoDescription',
      title: 'Globalny Opis SEO',
      type: 'text',
      description: 'Opis strony wyświetlany w wynikach wyszukiwania Google (max 160 znaków).',
      group: 'seo',
    }),
    defineField({
      name: 'seoKeywords',
      title: 'Keywords (Słowa kluczowe)',
      description: 'Po przecinku (np. piłka nożna, gdynia, klub)',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'gaId',
      title: 'Google Analytics ID (Opcjonalnie)',
      description: 'Twój identyfikator GA4 (np. G-XXXXXXXXXX). Jeśli dodasz, Google Analytics zostanie automatycznie aktywowany na stronie!',
      type: 'string',
      group: 'seo',
    }),
    defineField({
      name: 'seoImage',
      title: 'Domyślny Obrazek Udostępniania (OpenGraph)',
      type: 'image',
      description: 'Zdjęcie, które wyświetli się na Facebooku/Twitterze, gdy ktoś udostępni link do strony głównej.',
      options: { hotspot: true },
      group: 'seo',
    }),
  ],
})
